Main Header
===========
:Author:    David Allen
:Email:     <david.allen@neo4j.com>
:Date:      January 17 2018

= Recommendations
:user_name: 'Misty Williams'
:movie_name: 'Matrix'
:experimental:
:icon: font

== Intro To Cypher

In order to work with our labeled property graph, we need a query language for graphs. 

++++
<div class="col-lg-3 ng-scope">
++++
=== Graph Patterns

Cypher is the query language for graphs and is centered around *graph patterns*. Graph patterns are expressed in Cypher using ASCII-art like syntax.

*Nodes*

Nodes are defined within parentheses `()`. Optionally, we can specify node label(s): `(:Movie)`

*Relationships*

Relationships are defined within square brackets `[]`. Optionally we can specify type and direction:

`(:Movie)**+<-[:RATED]-+**(:User)`

*Aliases*

Graph elements can be bound to aliases that can be referred to later in the query:

`(**m**:Movie)+<-+[**r**:RATED]-(**u**:User)`

=== Predicates

Filters can be applied to these graph patterns to limit the matching paths. Boolean logic operators, regular expressions and string comparison operators can be used here.

=== Aggregations

There is an implicit group when using aggregation functions such as `COUNT`.

Be sure to use the link:https://neo4j.com/docs/cypher-refcard/current/?ref=browser-guide[Cypher Refcard] as a reference for learning Cypher syntax.


++++
</div>
++++

++++
<div class="col-lg-9 ng-scope">
++++

=== Dissecting a Cypher Statement
Let's look at a Cypher query that answers the question "How many reviews does each Matrix movie have?". Don't worry if this seems complex, we'll build up our understanding of Cypher as we move along. 

.How many reviews does each Matrix movie have? Click on the block to put the query in the top-most window on the query editor. Hit the triangular icon:play-circle[] button or press kbd:[Ctrl+Enter] to run it and see the resulting visualization.



[source,cypher]
----
MATCH (m:Movie)<-[:RATED]-(u:User)
WHERE m.title CONTAINS "Matrix"
WITH m.title AS movie, COUNT(*) AS reviews
RETURN movie, reviews
ORDER BY reviews DESC
LIMIT 5;
----

[width=100,cols="1,3,2"]
|===
| find      | `+MATCH (m:Movie)<-[:RATED]-(u:User)+`         | Search for an existing graph pattern
| filter    | `WHERE m.title CONTAINS "Matrix"`              | Filter matching paths to only those matching a predicate
| aggregate | `WITH m.title AS movie, COUNT(*) AS reviews`   | Count number of paths matched for each movie
| return    | `RETURN movie, reviews`                        | Specify columns to be returned by the statement
| order     | `ORDER BY reviews DESC`                        | Order by number of reviews, in descending order
| limit     | `LIMIT 5;`                                     | Only return first five records
|===



++++
</div>
++++

== Further Resources

++++
<div class="col-lg-6 ng-scope">
++++

=== Resources

* Web link:https://neo4j.com/docs/cypher-refcard/current/?ref=browser-guide[Cypher Refcard]
* Web link:https://neo4j.com/docs/?ref=browser-guide[Neo4j Documentation]
* Blog Post link:https://neo4j.com/blog/collaborative-filtering-creating-teams/?ref=browser-guide[Collaborative Filtering: Creating the Best Teams Ever]
* Video link:https://www.youtube.com/watch?v=b_0Iuc3zUN4[Bootstrapping Recommendations with Neo4j]
* Video link:https://www.youtube.com/watch?v=60E2WV4iwIg[Data Science and Recommendations]
* Video link:https://www.youtube.com/watch?v=VGCCVNlZmRI[Building a recommendation engine with Python and Neo4j]
* Web link:https://neo4j.com/use-cases/real-time-recommendation-engine/?ref=browser-guide[Solutions: Real-Time Recommendation Engines]
* Book (free download) link:http://graphdatabases.com/?ref=browser-guide[Graph Databases: New Opportunities for Connected Data]

++++
</div>
++++

++++
<div class="col-lg-6 ng-scope">
++++
=== Exercises

Extend these queries:

* **Temporal component**: Preferences change over time, use the rating timestamp to consider how more recent ratings might be used to find more relevant recommendations.
* **Keyword extraction**: Enhance the traits available using the plot description. How would you model extracted keywords for movies?
* **Image recognition using posters**: There are several libraries and APIs that offer image recognition and tagging. Since we have movie poster images for each movie, how could we use these to enhance our recomendations?

++++
</div>
++++
